pipeline:
  name: rn-expo-mobile
  identifier: rnexpomobile
  projectIdentifier: fever
  orgIdentifier: default
  timeout: 2h

  properties:
    ci:
      codebase:
        connectorRef: github_connector
        repoName: fever_mobile
        build: <+input>
      execution:
        concurrency:
          group: <+pipeline.sequenceId>-<+codebase.branch>
          cancel: true
      reportPaths: "**/*.xml"

  variables:
    - name: CHANNEL
      type: String
      description: EAS channel to publish to (develop/production)
      value: develop

  stages:
    # ---------------------------------------------------------------------
    # STAGE 1: VALIDATION (Runs for all scenarios)
    # ---------------------------------------------------------------------
    - stage:
        name: Validate
        identifier: Validate
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: install
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    command: |
                      corepack enable || true
                      npm ci

              - step:
                  type: Run
                  name: Lint and Test
                  identifier: test
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    command: |
                      npm run lint --if-present
                      npm test --if-present -- --ci

              - step:
                  type: Run
                  name: Local Build Check
                  identifier: local_build
                  spec:
                    shell: Sh
                    image: expo-selfhosted:latest
                    command: |
                      set -e
                      npm ci
                      npx expo start --non-interactive --offline --clear > expo.log 2>&1 &
                      EXPO_PID=$!
                      sleep 60
                      if curl -fsS http://127.0.0.1:19002 >/dev/null; then
                        echo "✅ Expo dev server started successfully."
                        kill $EXPO_PID
                        wait $EXPO_PID || true
                        exit 0
                      else
                        echo "❌ Expo dev server did not start. Recent logs:"
                        tail -n +200 expo.log || true
                        kill $EXPO_PID || true
                        exit 1
                      fi

    # ---------------------------------------------------------------------
    # STAGE 2: PRODUCTION BUILD (Only for merges to main)
    # ---------------------------------------------------------------------
    - stage:
        name: Production Build
        identifier: Production_Build
        type: CI
        when:
          pipelineStatus: Success
          condition: <+trigger.type> != "PullRequest" && <+codebase.branch> == "main"
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: Run
                  name: Expo Cloud Build - Android
                  identifier: eas_build_android_production
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                    command: |
                      corepack enable || true
                      npm ci
                      npx eas whoami
                      npx eas build --platform android --profile production --non-interactive

              - step:
                  type: Run
                  name: Expo Cloud Build - iOS
                  identifier: eas_build_ios_production
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                    command: |
                      corepack enable || true
                      npm ci
                      npx eas whoami
                      npx eas build --platform ios --profile production --non-interactive

    # ---------------------------------------------------------------------
    # STAGE 3: OTA UPDATE (Only for merges to main branch)
    # ---------------------------------------------------------------------
    - stage:
        name: OTA Update
        identifier: OTA_Update
        type: CI
        when:
          pipelineStatus: Success
          condition: <+trigger.type> != "PullRequest" && <+codebase.branch> == "main"
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          execution:
            steps:
              - step:
                  type: Run
                  name: EAS OTA Update
                  identifier: eas_update_production
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                    command: |
                      corepack enable || true
                      npm ci
                      npx eas whoami
                      npx eas update --channel "production" --non-interactive