pipeline:
  name: rn-expo-mobile
  identifier: rnexpomobile
  projectIdentifier: fever
  orgIdentifier: default
  timeout: 2h
  properties:
    ci:
      codebase:
        connectorRef: github_connector
        repoName: fever_mobile
        build: <+input>
      execution:
        concurrency:
          group: <+pipeline.sequenceId>-<+codebase.branch>
          cancel: true
      reportPaths: "**/*.xml"
  variables:
    - name: CHANNEL
      type: String
      description: EAS channel to publish to (develop/production)
      value: develop
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}     # <- added empty spec
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: install
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    command: |
                      corepack enable
                      npm ci

              - step:
                  type: Run
                  name: Lint and Test
                  identifier: test
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    command: |
                      npm run lint --if-present
                      npm test --if-present -- --ci

              - step:
                  type: Run
                  name: EAS Build Android Preview
                  identifier: eas_build_android_preview
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                    command: |
                      corepack enable
                      npm ci
                      npx eas whoami
                      npx eas build --platform android --profile preview --non-interactive

              - step:
                  type: Run
                  name: EAS Build Android Production
                  identifier: eas_build_android_production
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                    command: |
                      corepack enable
                      npm ci
                      npx eas whoami
                      npx eas build --platform android --profile production --non-interactive

              - step:
                  type: Run
                  name: EAS Build iOS Preview
                  identifier: eas_build_ios
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                    command: |
                      corepack enable
                      npm ci
                      npx eas whoami
                      npx eas build --platform ios --profile preview --non-interactive

    - stage:
        name: Deploy
        identifier: Deploy
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}     # <- added empty spec
          execution:
            steps:
              - step:
                  type: Run
                  name: EAS OTA Update
                  identifier: eas_update
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                      CHANNEL: <+pipeline.variables.CHANNEL>
                    command: |
                      corepack enable
                      npm ci
                      npx eas whoami
                      : "${CHANNEL:=develop}"
                      npx eas update --channel "${CHANNEL}" --non-interactive
