pipeline:
  name: rn-expo-mobile
  identifier: rnexpomobile
  projectIdentifier: fever
  orgIdentifier: default
  tags: {}
  timeout: 30m  # Pipeline will fail if it runs longer than 30 minutes
  properties:
    ci:
      codebase:
        connectorRef: github_connector
        repoName: fever_mobile
        build: <+input>
      execution:
        concurrency:
          group: <+pipeline.sequenceId>-<+codebase.branch>  # Unique group for each branch
          cancel: true  # Automatically cancels previous runs in same group
      reportPaths: "**/*.xml"  # For test reports if applicable
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: install
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    command: |
                      corepack enable
                      npm ci
              - step:
                  type: Run
                  name: Lint and Test
                  identifier: test
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    command: |
                      npm run lint --if-present
                      npm test --if-present -- --ci
              - step:
                  type: Run
                  name: EAS Build Android
                  identifier: eas_build_android
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                    command: |
                      npm i -g eas-cli
                      echo "Checking Expo account..."
                      eas whoami
                      eas build --platform android --profile preview --non-interactive
              - step:
                  type: Run
                  name: EAS Build iOS optional
                  identifier: eas_build_ios
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                    command: |
                      npm i -g eas-cli
                      echo "Checking Expo account..."
                      eas whoami
                      eas build --platform ios --profile preview --non-interactive
    - stage:
        name: Deploy
        identifier: Deploy
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: EAS OTA Update
                  identifier: eas_update
                  spec:
                    shell: Sh
                    image: node:20-bullseye
                    envVariables:
                      EAS_TOKEN: <+secrets.getValue("EAS_TOKEN")>
                      EXPO_TOKEN: <+secrets.getValue("EXPO_TOKEN")>
                      CHANNEL: <+pipeline.variables.CHANNEL>
                    command: |
                      npm i -g eas-cli
                      echo "Checking Expo account..."
                      eas whoami
                      : "${CHANNEL:=develop}"
                      eas update --channel "${CHANNEL}" --non-interactive
  variables:
    - name: CHANNEL
      type: String
      description: EAS channel to publish to (develop/production)
      value: develop