trigger:
  name: main_pull_request
  identifier: main_pull_request
  enabled: true
  description: Trigger on PR to main - runs Build stage only
  tags: {}
  orgIdentifier: default
  projectIdentifier: fever
  pipelineIdentifier: rnexpomobile
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: github_connector
          repoName: fever_mobile
          actions:
            - Open
            - Reopen
            - Synchronize
          targetBranch: main
  inputSetRefs:
    - main_pull_request_inputset


inputSet:
  name: main_pull_request_inputset
  identifier: main_pull_request_inputset
  orgIdentifier: default
  projectIdentifier: fever
  pipeline:
    identifier: rnexpomobile
    stages:
      - stage:
          identifier: Build
          type: CI
          spec:
            cloneCodebase: true
