trigger:
  name: main_merge
  identifier: main_merge
  enabled: true
  description: Trigger on merge to main - runs all stages
  tags: {}
  orgIdentifier: default
  projectIdentifier: fever
  pipelineIdentifier: rnexpomobile
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: Push
        spec:
          connectorRef: github_connector
          repoName: fever_mobile
          branch: main
  inputSetRefs:
    - main_merge_inputset

inputSet:
  name: main_merge_inputset
  identifier: main_merge_inputset
  orgIdentifier: default
  projectIdentifier: fever
  pipeline:
    identifier: rnexpomobile
    stages:
      - stage:
          identifier: Build
          type: CI
          spec:
            cloneCodebase: true
      - stage:
          identifier: Deploy
          type: CI
          spec:
            cloneCodebase: true
